name: CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest # Indicas que el trabajo se realizara en una VM con la ultima version de ubuntu
        steps:
          - name: Checkout code 
            uses: actions/checkout@v2 # El primer paso sera clonar el repositorio en esta VM
          - name: Set Up Node.js
            uses: actions/setup-node@v2 # El segundo paso será instalar node version 14
            with:
                node-version: '14'
          - name: Install dependencies # Literalmente instalar las dependencias necesarias
            run: npm install
          - name: Run tests # Ejecutamos npm test en la VM
            run: npm test
          #Pasos Adicionales para la configuracion continua
          - name: Build Docker image # Literal lo dice xd
            run: docker build -t devops-practice .
          - name: Running Docker image # Iniciamos el servidor en el puerto 3000
            run: docker run -p 3001:3001 devops-practice