name: CI/CD Pipeline

on:
    push:
        branches:
            -main
    pull_request:
        branches:
            -main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code # Clonación del repositorio
              uses: actions/checkout@v2s
            - name: Set up node js
              uses: actions/setup-node@v2
              with:
                node-version: "14"
            - name: Install dependencies
              run: npm install
            - name: Running test
              run: npm test
            - name: Run security script
              run: npm audit
            # Construir la imagen 
            - name: Build docker image
              run: docker build -t devops-practice2 .
            - name: Run docker image
              run: docker run -p 3000:3000 devops-practice2
            