name: CI/CD Pipeline

on:
    push:
        branches:
            -main
    pull_request:
        branches:
            -main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code # Clonación del repositorio
              uses: actions/checkout@v2s
            - name: Set up node js
              uses: actions/setup-node@v2
              with:
                node-version: "14"
            - name: Install dependencies
              run: npm install
              working-directory: "Actividad2/devops-practice"
            - name: Running test
              run: npm test
            - name: Run security script
              run: npm audit
            # Ejecutar Docker Compose
            - name: Build and run docker compose
              run: docker compose up --build -d
           # Para ejecucion de Docker Compose
            - name: Stop and clean Docker Compose
              run: docker compose down
